In [1]:
import numpy as np
from sklearn import linear_model
import pandas as pd

In [2]:
df= pd.read_csv('homeprices.csv')
df

,area,price
0,2600,550000
1,3000,565000
2,3200,610000
3,3600,680000
4,4000,725000


In [3]:
reg = linear_model.LinearRegression()
reg.fit(df[['area']],df.price)

LinearRegression()

In [4]:
reg.coef_

array([135.78767123])

In [5]:
reg.intercept_

np.float64(180616.43835616432)

In [7]:
reg.predict([[5000]])

C:\Users\itiks\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [8]:
import pickle

In [9]:
with open('reg_pickle','wb') as f:
    pickle.dump(reg,f)

In [10]:
with open('reg_pickle','rb') as f:
    mp= pickle.load(f)

In [11]:
mp.predict([[5000]])

C:\Users\itiks\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [14]:
import joblib

In [15]:
joblib.dump(reg,'reg.joblib')

['reg.joblib']

In [16]:
rj= joblib.load(reg,'reg.joblib')

TypeError: expected str, bytes or os.PathLike object, not LinearRegression